var myName = "Daryl Gilmore";
/*
function(yes) {
  alert(yes);
}();
*/

console.log(myName);
console.log("MY GOAL IS TO LEARN AS MUCH AS POSSIBLE ABOUT BUILDING WEBSITES, CYBER SECURITY AND ALL AROUND COMPUTTER KNOWLEDGE. MY FAVORITE HOBBY, THAT'S HARD TO SAY FISHING/PISMO DUNES/SWIMMING I HAVE A FEW." )
